# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'app.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
#
# AUTHOR - ADRISKK
# GITHUB LINK -----  https://github.com/Adriskk/FakeIDGeneratorApp/



from PyQt5 import QtCore, QtGui, QtWidgets
from random_identity import identity
from random_identity.data import DataClass as dataC


class Ui_MainWindow(object):
    def __init__(self):
        self.generateTxtFile = False

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(774, 520)

        MainWindow.setMinimumSize(QtCore.QSize(750, 520))
        MainWindow.setMaximumSize(QtCore.QSize(760, 700))

        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ico/id.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)

        MainWindow.setWindowIcon(icon)
        MainWindow.setWindowOpacity(1.0)
        MainWindow.setStyleSheet("background-color: rgb(56, 56, 56);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(620, 420))
        self.centralwidget.setMaximumSize(QtCore.QSize(818, 496))

        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 781, 501))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.appTitle = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.appTitle.setMaximumSize(QtCore.QSize(1000, 55))
        self.appTitle.setStyleSheet("font: 25 14pt \"Yu Gothic UI Light\";\n"
                                    "color: rgb(255, 255, 255);\n"
                                    "background-color: rgb(48, 48, 48);")
        self.appTitle.setObjectName("appTitle")
        self.verticalLayout.addWidget(self.appTitle)
        self.topBarLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.topBarLabel.setEnabled(True)
        self.topBarLabel.setMinimumSize(QtCore.QSize(650, 30))
        self.topBarLabel.setMaximumSize(QtCore.QSize(16777215, 40))
        self.topBarLabel.setStyleSheet("background-color: rgb(48, 48, 48);\n"
                                       "border-bottom: 3px solid qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 0, 0, 255), stop:0.166 rgba(255, 255, 0, 255), stop:0.333 rgba(0, 255, 0, 255), stop:0.5 rgba(0, 255, 255, 255), stop:0.666 rgba(0, 0, 255, 255), stop:0.833 rgba(255, 0, 255, 255), stop:1 rgba(255, 0, 0, 255));;")
        self.topBarLabel.setText("")
        self.topBarLabel.setScaledContents(False)
        self.topBarLabel.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTop | QtCore.Qt.AlignTrailing)
        self.topBarLabel.setObjectName("topBarLabel")
        self.verticalLayout.addWidget(self.topBarLabel)
        self.Content = QtWidgets.QVBoxLayout()
        self.Content.setSpacing(6)
        self.Content.setObjectName("Content")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.line_5 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line_5.setMaximumSize(QtCore.QSize(450, 16777215))
        self.line_5.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.gridLayout.addWidget(self.line_5, 10, 0, 1, 1)
        self.line_7 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line_7.setMaximumSize(QtCore.QSize(400, 16777215))
        self.line_7.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.gridLayout.addWidget(self.line_7, 12, 0, 1, 1)
        self.titleInput = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.titleInput.setMaximumSize(QtCore.QSize(200, 40))
        self.titleInput.setStyleSheet("\n"
                                      "font: 63 18pt \"Yu Gothic UI Semibold\";\n"
                                      "color: rgb(255, 255, 255);")
        self.titleInput.setObjectName("titleInput")
        self.gridLayout.addWidget(self.titleInput, 0, 0, 1, 1)
        self.line = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line.setMaximumSize(QtCore.QSize(300, 16777215))
        self.line.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 2, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_9.setMaximumSize(QtCore.QSize(100, 30))
        self.label_9.setStyleSheet("font: 57 9pt \"Yu Gothic Medium\";\n"
                                   "color: rgb(255, 255, 255);")
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 13, 0, 1, 1)
        self.line_4 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line_4.setMaximumSize(QtCore.QSize(200, 16777215))
        self.line_4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout.addWidget(self.line_4, 8, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setMaximumSize(QtCore.QSize(100, 30))
        self.label.setStyleSheet("font: 57 9pt \"Yu Gothic Medium\";\n"
                                 "color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 3, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_5.setMaximumSize(QtCore.QSize(100, 30))
        self.label_5.setStyleSheet("font: 57 9pt \"Yu Gothic Medium\";\n"
                                   "color: rgb(255, 255, 255);")
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 9, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_4.setMaximumSize(QtCore.QSize(100, 30))
        self.label_4.setStyleSheet("font: 57 9pt \"Yu Gothic Medium\";\n"
                                   "color: rgb(255, 255, 255);")
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 7, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_8.setMaximumSize(QtCore.QSize(100, 30))
        self.label_8.setStyleSheet("font: 57 9pt \"Yu Gothic Medium\";\n"
                                   "color: rgb(255, 255, 255);")
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 11, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_6.setMaximumSize(QtCore.QSize(100, 30))
        self.label_6.setStyleSheet("font: 57 9pt \"Yu Gothic Medium\";\n"
                                   "color: rgb(255, 255, 255);")
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 15, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_3.setMaximumSize(QtCore.QSize(100, 30))
        self.label_3.setStyleSheet("font: 57 9pt \"Yu Gothic Medium\";\n"
                                   "color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 5, 0, 1, 1)
        self.line_3 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line_3.setMaximumSize(QtCore.QSize(300, 16777215))
        self.line_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout.addWidget(self.line_3, 6, 0, 1, 1)
        self.checkBox = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.checkBox.setMaximumSize(QtCore.QSize(120, 16777215))
        self.checkBox.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox.setObjectName("checkBox")
        self.gridLayout.addWidget(self.checkBox, 0, 1, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line_2.setMaximumSize(QtCore.QSize(380, 16777215))
        self.line_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 4, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setMaximumSize(QtCore.QSize(100, 30))
        self.label_2.setStyleSheet("font: 57 9pt \"Yu Gothic Medium\";\n"
                                   "color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.line_8 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line_8.setMaximumSize(QtCore.QSize(250, 16777215))
        self.line_8.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.gridLayout.addWidget(self.line_8, 14, 0, 1, 1)
        self.fullName = QtWidgets.QTextEdit(self.verticalLayoutWidget)
        self.fullName.setMaximumSize(QtCore.QSize(150, 30))
        self.fullName.setStyleSheet("color: rgb(255, 255, 255);")
        self.fullName.setObjectName("fullName")
        self.gridLayout.addWidget(self.fullName, 1, 1, 1, 1)
        self.birthday = QtWidgets.QTextEdit(self.verticalLayoutWidget)
        self.birthday.setMaximumSize(QtCore.QSize(120, 30))
        self.birthday.setStyleSheet("color: rgb(255, 255, 255);")
        self.birthday.setObjectName("birthday")
        self.gridLayout.addWidget(self.birthday, 3, 1, 1, 1)
        self.age = QtWidgets.QTextEdit(self.verticalLayoutWidget)
        self.age.setMaximumSize(QtCore.QSize(50, 30))
        self.age.setStyleSheet("color: rgb(255, 255, 255);")
        self.age.setObjectName("age")
        self.gridLayout.addWidget(self.age, 5, 1, 1, 1)
        self.phoneNumber = QtWidgets.QTextEdit(self.verticalLayoutWidget)
        self.phoneNumber.setMaximumSize(QtCore.QSize(90, 30))
        self.phoneNumber.setStyleSheet("color: rgb(255, 255, 255);")
        self.phoneNumber.setObjectName("phoneNumber")
        self.gridLayout.addWidget(self.phoneNumber, 7, 1, 1, 1)
        self.nationality = QtWidgets.QTextEdit(self.verticalLayoutWidget)
        self.nationality.setMaximumSize(QtCore.QSize(150, 30))
        self.nationality.setStyleSheet("color: rgb(255, 255, 255);")
        self.nationality.setObjectName("nationality")
        self.gridLayout.addWidget(self.nationality, 9, 1, 1, 1)
        self.workplace = QtWidgets.QTextEdit(self.verticalLayoutWidget)
        self.workplace.setMaximumSize(QtCore.QSize(200, 30))
        self.workplace.setStyleSheet("color: rgb(255, 255, 255);")
        self.workplace.setObjectName("workplace")
        self.gridLayout.addWidget(self.workplace, 11, 1, 1, 1)
        self.eMail = QtWidgets.QTextEdit(self.verticalLayoutWidget)
        self.eMail.setMaximumSize(QtCore.QSize(180, 30))
        self.eMail.setStyleSheet("color: rgb(255, 255, 255);")
        self.eMail.setObjectName("eMail")
        self.gridLayout.addWidget(self.eMail, 13, 1, 1, 1)
        self.address = QtWidgets.QTextEdit(self.verticalLayoutWidget)
        self.address.setMaximumSize(QtCore.QSize(400, 30))
        self.address.setStyleSheet("color: rgb(255, 255, 255);")
        self.address.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.address.setObjectName("address")
        self.gridLayout.addWidget(self.address, 15, 1, 1, 1)
        self.generateButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.generateButton.setMinimumSize(QtCore.QSize(0, 20))
        self.generateButton.setMaximumSize(QtCore.QSize(68, 30))
        self.generateButton.setStyleSheet("color: rgb(255, 255, 255);\n"
                                          "background-color: rgb(93, 93, 93);\n"
                                          "border-radius: 3px;\n"
                                          "")
        self.generateButton.setObjectName("generateButton")
        self.gridLayout.addWidget(self.generateButton, 0, 3, 1, 1)
        self.Content.addLayout(self.gridLayout)
        self.verticalLayout.addLayout(self.Content)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        # CHECKBOX  STATEMENT
        self.checkBox.stateChanged.connect(self.checkBoxClicked)
        # BUTTON
        self.generateButton.clicked.connect(self.raiseData)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def raiseData(self):
        data = dataC.Data()
        data.setupData(self.fullName, self.birthday, self.age, self.phoneNumber, self.nationality, self.workplace, self.eMail, self.address)

        if self.generateTxtFile:
            data.generateFile()

    def checkBoxClicked(self, state):
        if state == QtCore.Qt.Checked:
            self.generateTxtFile = True
        else:
            self.generateTxtFile = False

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Random Identity Generator"))
        self.appTitle.setText(_translate("MainWindow",
            "<html><head/><body><p><span style=\" font-weight:600;\"><span style=\"color: #c0392b;\">Random</span><span style=\"color: #e67e22;\"> Identity</span></span> <span style=\"color: #f1c40f;\">Generator</span></p></body></html>"))
        self.titleInput.setText(_translate("MainWindow",
            "<html><head/><body><p><span style=\" font-weight:600; color:#d35400;\">Fake </span><span style=\" font-weight:296; color:#f1c40f;\">ID:</span></p></body></html>"))
        self.label_9.setText(_translate("MainWindow",
            "<html><head/><body><p><span style=\" font-weight:600;\"> E</span>-mail:</p></body></html>"))
        self.label.setText(_translate("MainWindow",
            "<html><head/><body><p><span style=\" font-weight:600;\"> B</span>irthday</p></body></html>"))
        self.label_5.setText(_translate("MainWindow",
            "<html><head/><body><p><span style=\" font-weight:600;\"> N</span>ationality:</p></body></html>"))
        self.label_4.setText(_translate("MainWindow",
            "<html><head/><body><p><span style=\" font-weight:600;\"> P</span>hone number: </p></body></html>"))
        self.label_8.setText(_translate("MainWindow",
            "<html><head/><body><p><span style=\" font-weight:600;\">  W</span>orkplace: </p></body></html>"))
        self.label_6.setText(_translate("MainWindow",
            "<html><head/><body><p><span style=\" font-weight:600;\"> A</span>ddress:</p></body></html>"))
        self.label_3.setText(_translate("MainWindow",
            "<html><head/><body><p><span style=\" font-weight:600;\">A</span>ge: </p></body></html>"))
        self.checkBox.setText(_translate("MainWindow", "Generate a txt file"))
        self.label_2.setText(_translate("MainWindow",
            "<html><head/><body><p><span style=\" font-weight:600;\">  F</span>ull name: </p></body></html>"))
        self.generateButton.setText(_translate("MainWindow", "Generate"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
